'use client'

import type { DeliveryRow } from '@/lib/queries/delivery'

interface Props {
  logs: DeliveryRow[]
  stats: { total: number; sent: number; simulated: number; failed: number; pending: number }
}

const TYPE_LABELS: Record<string, string> = {
  invite: 'Invite',
  password_reset: 'Password Reset',
  staffing_alert: 'Staffing Alert',
}

const STATUS_STYLES: Record<string, string> = {
  sent: 'bg-green-100 text-green-800',
  simulated: 'bg-blue-100 text-blue-800',
  failed: 'bg-red-100 text-red-800',
  pending: 'bg-yellow-100 text-yellow-800',
}

function formatDate(d: Date | string): string {
  return new Date(d).toLocaleString(undefined, {
    dateStyle: 'medium',
    timeStyle: 'short',
  })
}

export default function DeliveryLogView({ logs, stats }: Props) {
  return (
    <div className="p-6 max-w-5xl mx-auto space-y-6">
      <div>
        <h1 className="text-2xl font-semibold text-gray-900">Delivery Log</h1>
        <p className="text-sm text-gray-500 mt-1">
          Transactional messages generated by the system.
        </p>
      </div>

      {/* Stats row */}
      <div className="grid grid-cols-2 sm:grid-cols-5 gap-3">
        {[
          { label: 'Total', value: stats.total, style: 'text-gray-900' },
          { label: 'Sent', value: stats.sent, style: 'text-green-700' },
          { label: 'Simulated', value: stats.simulated, style: 'text-blue-700' },
          { label: 'Failed', value: stats.failed, style: 'text-red-700' },
          { label: 'Pending', value: stats.pending, style: 'text-yellow-700' },
        ].map((s) => (
          <div key={s.label} className="bg-white rounded-lg border border-gray-200 px-4 py-3">
            <p className="text-xs text-gray-500 uppercase tracking-wide">{s.label}</p>
            <p className={`text-2xl font-semibold mt-1 ${s.style}`}>{s.value}</p>
          </div>
        ))}
      </div>

      {/* Table */}
      <div className="bg-white rounded-lg border border-gray-200 overflow-hidden">
        {logs.length === 0 ? (
          <div className="py-16 text-center text-gray-400 text-sm">
            No delivery records yet.
          </div>
        ) : (
          <table className="min-w-full divide-y divide-gray-200 text-sm">
            <thead className="bg-gray-50">
              <tr>
                {['Date', 'Type', 'Recipient', 'Subject', 'Status'].map((h) => (
                  <th
                    key={h}
                    className="px-4 py-3 text-left text-xs font-semibold text-gray-600 uppercase tracking-wide"
                  >
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {logs.map((log) => (
                <tr key={log.id} className="hover:bg-gray-50 transition-colors">
                  <td className="px-4 py-3 text-gray-500 whitespace-nowrap">
                    {formatDate(log.createdAt)}
                  </td>
                  <td className="px-4 py-3 whitespace-nowrap">
                    <span className="text-gray-700">{TYPE_LABELS[log.type] ?? log.type}</span>
                  </td>
                  <td className="px-4 py-3 text-gray-700 max-w-[200px] truncate">
                    {log.recipient}
                  </td>
                  <td className="px-4 py-3 text-gray-600 max-w-[260px] truncate">
                    {log.subject}
                  </td>
                  <td className="px-4 py-3 whitespace-nowrap">
                    <span
                      className={`inline-flex items-center px-2 py-0.5 rounded text-xs font-medium ${
                        STATUS_STYLES[log.status] ?? 'bg-gray-100 text-gray-700'
                      }`}
                    >
                      {log.status}
                    </span>
                    {log.errorMessage && (
                      <p className="text-xs text-red-500 mt-0.5 max-w-[200px] truncate" title={log.errorMessage}>
                        {log.errorMessage}
                      </p>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>

      {logs.length > 0 && (
        <p className="text-xs text-gray-400 text-right">
          Showing latest {logs.length} record{logs.length !== 1 ? 's' : ''}
        </p>
      )}
    </div>
  )
}
